# Generated by Django 3.2.9 on 2022-06-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='car_brand', to='parking.brand'),
        ),
        migrations.AlterField(
            model_name='parkingcharge',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parked_car', to='parking.parkingtracking'),
        ),
        migrations.AlterField(
            model_name='parkingtracking',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tracked_activity', to='parking.activity'),
        ),
        migrations.AlterField(
            model_name='parkingtracking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tracked_car', to='parking.car'),
        ),
    ]
