# Generated by Django 3.2.9 on 2022-07-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingreport',
            name='entrance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingreport',
            name='exit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingreport',
            name='parking',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
