# Generated by Django 3.2.9 on 2022-07-23 01:15

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20220723_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingreport',
            options={'verbose_name': 'Parking Report', 'verbose_name_plural': 'Parking Report'},
        ),
        migrations.AlterField(
            model_name='parkingreport',
            name='charge',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='TZS', max_digits=14, null=True),
        ),
    ]
