# Generated by Django 3.2.9 on 2022-07-23 01:30

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20220723_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingreport',
            name='charge',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='TZS', max_digits=14),
        ),
    ]
